    
version: 2.1

defaults: &defaults
  working_directory: /go/src/github.com/contbank/bankly-sdk
commands:
  autotag:
    steps:
      - run: |
          make install-autotag
jobs:
  run-tests:
    <<: *defaults
    docker:
    - image: circleci/golang:1.14
    environment:
     - BANKLY_CLIENT_ID: ${BANKLY_CLIENT_ID}
     - BANKLY_CLIENT_SECRET: ${BANKLY_CLIENT_SECRET}
    steps:
      - checkout
      - run:
          name: Run Rebase
          command: make run-rebase
      - run:
          name: Build Package
          command: make build-package
      - run:
          name: Run Tests
          command: make run-tests
  release-vesion:
    <<: *defaults
    docker:
    - image: circleci/golang:1.14
    steps:
      - add_ssh_keys:
          fingerprints:
            - 9a:b3:df:33:d0:b0:d7:55:c9:7d:e3:55:58:e4:88:13
      - checkout
      - autotag
      - run:
          name: Tag Git Version
          command: make tag-version

workflows:
  version: 2
  build-deploy:
    jobs:
      - run-tests

      - release-vesion:
          context: SANDBOX
          requires:
            - run-tests
          filters:
            branches:
              only:
                - master