// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	http "net/http"

	logrus "github.com/sirupsen/logrus"
	mock "github.com/stretchr/testify/mock"
)

// ErrorHandler is an autogenerated mock type for the ErrorHandler type
type ErrorHandler struct {
	mock.Mock
}

type ErrorHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *ErrorHandler) EXPECT() *ErrorHandler_Expecter {
	return &ErrorHandler_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: fields, resp
func (_m *ErrorHandler) Execute(fields logrus.Fields, resp *http.Response) error {
	ret := _m.Called(fields, resp)

	var r0 error
	if rf, ok := ret.Get(0).(func(logrus.Fields, *http.Response) error); ok {
		r0 = rf(fields, resp)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ErrorHandler_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type ErrorHandler_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//  - fields logrus.Fields
//  - resp *http.Response
func (_e *ErrorHandler_Expecter) Execute(fields interface{}, resp interface{}) *ErrorHandler_Execute_Call {
	return &ErrorHandler_Execute_Call{Call: _e.mock.On("Execute", fields, resp)}
}

func (_c *ErrorHandler_Execute_Call) Run(run func(fields logrus.Fields, resp *http.Response)) *ErrorHandler_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(logrus.Fields), args[1].(*http.Response))
	})
	return _c
}

func (_c *ErrorHandler_Execute_Call) Return(_a0 error) *ErrorHandler_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

type mockConstructorTestingTNewErrorHandler interface {
	mock.TestingT
	Cleanup(func())
}

// NewErrorHandler creates a new instance of ErrorHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewErrorHandler(t mockConstructorTestingTNewErrorHandler) *ErrorHandler {
	mock := &ErrorHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
